baseURL = '/'
languageCode = 'zh-CN'
title = 'PIEEG - 低成本脑机接口设备'
defaultContentLanguage = 'zh-cn'

[params]
  description = "PIEEG提供易于使用和购买的低成本脑机接口设备，让神经科学研究变得触手可及"
  keywords = "脑机接口,EEG,EMG,ECG,Raspberry Pi,Arduino,Jetson Nano,神经科学"
  author = "PIEEG Team"
  
  # 版权信息配置
  [params.copyright]
    company = "PIEEG.CN"
    year = "2025"
    owner = "PIEEG.CN"
    
  # 中国备案信息配置
  [params.icp]
    enabled = true
    number = "沪ICP备2025127930号-1"  # 请替换为实际的ICP备案号
    url = "https://beian.miit.gov.cn/"
    
  # 公安备案信息配置（可选）
  [params.gongan]
    enabled = false
    number = "京公网安备 11010502012345号"  # 请替换为实际的公安备案号
    url = "http://www.beian.gov.cn/"
    
  # 网站分析配置
  [params.analytics]
    # 百度统计
    [params.analytics.baidu]
      enabled = true
      site_id = "your_baidu_site_id_here"  # 请替换为您的百度统计站点ID
    
    # Google Analytics（可选）
    [params.analytics.google]
      enabled = false
      tracking_id = ""  # 如需使用请填入GA跟踪ID
  
  # 联系信息配置
  [params.contact]
    # 邮件联系
    [params.contact.email]
      title = "邮件联系"
      description = "技术支持和产品咨询"
      sales_email = "sales@pieeg.cn"
      support_email = "support@pieeg.cn"
      icon = "fas fa-envelope"
    
    # 联系电话
    [params.contact.phone]
      title = "联系电话"
      description = "产品及合作咨询"
      phone1 = "+86 18516515688"
      phone2 = "+86 18616060956"
      icon = "fas fa-phone"
    
      # 微信联系
  [params.contact.wechat]
    title = "微信联系"
    description = "扫码添加微信咨询"
    qr_image = "/images/wechat.png"
    text = "微信咨询"
    icon = "fab fa-weixin"

# 产品购买链接配置
[params.shop_links]
  pieeg-8 = "https://item.taobao.com/item.htm?ft=t&id=851774011363&spm=a21dvs.23580594.0.0.1d292c1bBHzBJR"
  pieeg-16 = "https://item.taobao.com/item.htm?ft=t&id=864234733470&spm=a21dvs.23580594.0.0.1d292c1bBHzBJR"
  education-kit = "https://item.taobao.com/item.htm?ft=t&id=904720744382&skuId=5764038685450&spm=a21dvs.23580594.0.0.1d292c1bBHzBJR"
  ardeeg = "https://item.taobao.com/item.htm?ft=t&id=864181370108&spm=a21dvs.23580594.0.0.1d292c1bBHzBJR"
  jneeg = "https://item.taobao.com/item.htm?spm=a21dvs.23580594.0.0.1d292c1bBHzBJR&ft=t&id=864656349358"

# Footer资源链接配置
[params.footer_resources]
  [[params.footer_resources.links]]
    name = "技术文档"
    url = "https://pieeg.com/docs/docs/"
    external = true
  
  [[params.footer_resources.links]]
    name = "GitHub代码"
    url = "https://github.com/pieeg-club"
    external = true
  
  [[params.footer_resources.links]]
    name = "教程资源"
    url = "https://pieeg.com/case/"
    external = true
  
  [[params.footer_resources.links]]
    name = "免责声明"
    url = "/disclaimer/"
    external = false

# Footer社交媒体配置
[params.footer_social]
  [[params.footer_social.links]]
    name = "GitHub"
    url = "https://github.com/pieeg-club"
    icon = "fab fa-github"
  
  [[params.footer_social.links]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCVF-3Bp34LINLOQsyWNpcow"
    icon = "fab fa-youtube"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 10
  [[menu.main]]
  name = "产品"
  url = "/products/"
  weight = 20
  [[menu.main]]
    name = "数据可视化"
    url = "/#charts"
    weight = 30
  [[menu.main]]
    name = "关于我们"
    url = "/about/"
    weight = 40

# 禁用默认分类系统（如categories和tags）
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
